services:
  php-server:
    build: .
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:4001:4000"
    depends_on:
      - db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
  db:
    image: mysql:9.4.0
    volumes:
      - db_data:/var/lib/mysql
      - ./dbInit.sql:/docker-entrypoint-initdb.d/dbInit.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DATABASE}

volumes:
  db_data:
