services:
  php-server:
    build: .
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:4001:4000"
    depends_on:
      - db

  db:
    image: mysql:9.4.0
    volumes:
      - db_data:/var/lib/mysql
      - ./dbInit.sql:/docker-entrypoint-initdb.d/dbInit.sql
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: contactdb

volumes:
  db_data:

# update later with this config: https://docs.docker.com/guides/php/develop/
